[package]
name = "addr2linec"
version = "0.1.0"
edition = "2024"

[lib]
# name = "rscp"
# not "lib",
# and not cdylib for lack `pub fn` symbols, only extern symbols
crate-type = ["dylib", "staticlib"]

[dependencies]
addr2line = "0.25"
libc = "0.2.177"
